// Traduz textos PT -> EN no frame selecionado
// Detecta palavras/frases PT e substitui — ignora termos técnicos e inglês
const translations = {
  // Frame anterior (MCP config)
  'Dados da configuração':           'Configuration Data',
  'Configurar Trigger - MCP Server': 'Configure Trigger - MCP Server',
  'Agente Atendimento TIM':          'TIM Attendance Agent',
  'Nome do servidor':                'Server Name',
  'Obrigatório':                     'Required',
  'rótulo':                          'label',
  'Versão':                          'Version',
  'Tempo limite':                    'Timeout',
  'FERRAMENTAS':                     'TOOLS',
  '+ Adicionar Ferramenta':          '+ Add Tool',
  'Excluir':                         'Delete',
  'Opção 1':                         'Option 1',
  'PROPRIEDADES':                    'PROPERTIES',
  'Nome':                            'Name',
  'Descrição':                       'Description',
  'Consulta o status de um pedido':  'Query the status of an order',
  '+ Adicionar':                     '+ Add',
  'Adicionar':                       'Add',
  'Cancelar':                        'Cancel',
  'Precisa de ajuda?':               'Need help?',
  'Ver perfil':                      'View profile',
  // Frame atual (Plugins)
  'Novo Plugin':                     'New Plugin',
  'Ambiente':                        'Environment',
  'Configurações do Plugin':         'Plugin Settings',
  'CONFIGURAÇÃO BÁSICA':             'BASIC CONFIGURATION',
  'Escolha uma opção':               'Choose an option',
  'AUTENTICAÇÃO':                    'AUTHENTICATION',
  'COMPORTAMENTO DO MODELO':         'MODEL BEHAVIOR',
  'RASTREAMENTO DE CUSTOS':          'COST TRACKING',
  'CONFIGURAÇÕES TÉCNICAS':          'TECHNICAL SETTINGS',
  'Configurações do plugin':         'Plugin settings',
  'Configuração básica':             'Basic configuration',
  'Autenticação':                    'Authentication',
  'Comportamento do modelo':         'Model behavior',
  'Rastreamento de custos':          'Cost tracking',
  'Configurações técnicas':          'Technical settings',
  'Insira':                          'Enter',
  'Parâmetros Avançados':            'Advanced Parameters',
  'Habilitado':                      'Enabled',
  'Desabilitado':                    'Disabled',
  'Obrigatório':                     'Required',
  'Opcional':                        'Optional',
  'Ocultar Conteúdo':                'Hide Content',
  'Mostrar Conteúdo':                'Show Content',
  'Adicionar campo':                 'Add field',
  'Adicionar parâmetro':             'Add parameter',
  'Adicionar cabeçalho':             'Add header',
  'Chave de autenticação':           'Authentication key',
  'Valor de autenticação':           'Authentication value',
  'Método HTTP':                     'HTTP Method',
  'Corpo da requisição':             'Request body',
  'Cabeçalhos':                      'Headers',
  'Cabeçalho':                       'Header',
  'Parâmetro':                       'Parameter',
  'Parâmetros':                      'Parameters',
  'Avançado':                        'Advanced',
  'Avançados':                       'Advanced',
  'Básico':                          'Basic',
  'Tipo de autenticação':            'Authentication type',
  'Sem autenticação':                'No authentication',
  'Testar conexão':                  'Test connection',
  'Teste':                           'Test',
  'Intervalo':                       'Interval',
  'Frequência':                      'Frequency',
  'Agendamento':                     'Schedule',
  'Executar agora':                  'Run now',
  'Executar':                        'Run',
  'Pausar':                          'Pause',
  'Retomar':                         'Resume',
  'Reiniciar':                       'Restart',
  'Recarregar':                      'Reload',
  'Atualizar página':                'Refresh page',
  'Página':                          'Page',
  'Próxima página':                  'Next page',
  'Página anterior':                 'Previous page',
  'Resultados por página':           'Results per page',
  'de':                              'of',
  'itens':                           'items',
  'Exibir':                          'Show',
  'Ocultar':                         'Hide',
  'Expandir':                        'Expand',
  'Recolher':                        'Collapse',
  'Abrir':                           'Open',
  'Fechar':                          'Close',
  'Descrição de uma mensagem':       'Message description',
  'Plugins':                         'Plugins',
  'Ativo':                           'Active',
  'Inativo':                         'Inactive',
  'Ativar':                          'Enable',
  'Desativar':                       'Disable',
  'Editar':                          'Edit',
  'Remover':                         'Remove',
  'Salvar':                          'Save',
  'Fechar':                          'Close',
  'Confirmar':                       'Confirm',
  'Voltar':                          'Back',
  'Próximo':                         'Next',
  'Anterior':                        'Previous',
  'Buscar':                          'Search',
  'Filtrar':                         'Filter',
  'Ordenar':                         'Sort',
  'Carregando...':                   'Loading...',
  'Carregando':                      'Loading',
  'Erro':                            'Error',
  'Sucesso':                         'Success',
  'Aviso':                           'Warning',
  'Informação':                      'Information',
  'Configurações':                   'Settings',
  'Configuração':                    'Configuration',
  'Tipo':                            'Type',
  'Status':                          'Status',
  'Ações':                           'Actions',
  'Ação':                            'Action',
  'Título':                          'Title',
  'Conteúdo':                        'Content',
  'Mensagem':                        'Message',
  'Valor':                           'Value',
  'Chave':                           'Key',
  'Token':                           'Token',
  'Usuário':                         'User',
  'Senha':                           'Password',
  'Email':                           'Email',
  'Telefone':                        'Phone',
  'Endereço':                        'Address',
  'País':                            'Country',
  'Estado':                          'State',
  'Cidade':                          'City',
  'CEP':                             'ZIP Code',
  'Data':                            'Date',
  'Hora':                            'Time',
  'Criado em':                       'Created at',
  'Atualizado em':                   'Updated at',
  'Criado por':                      'Created by',
  'Atualizado por':                  'Updated by',
  'Visualizar':                      'View',
  'Detalhes':                        'Details',
  'Resumo':                          'Summary',
  'Total':                           'Total',
  'Subtotal':                        'Subtotal',
  'Nenhum resultado encontrado':     'No results found',
  'Sem dados':                       'No data',
  'Não encontrado':                  'Not found',
  'Acesso negado':                   'Access denied',
  'Entrar':                          'Sign in',
  'Sair':                            'Sign out',
  'Cadastrar':                       'Sign up',
  'Esqueci minha senha':             'Forgot my password',
  'Sim':                             'Yes',
  'Não':                             'No',
  'OK':                              'OK',
  'Aplicar':                         'Apply',
  'Limpar':                          'Clear',
  'Resetar':                         'Reset',
  'Importar':                        'Import',
  'Exportar':                        'Export',
  'Download':                        'Download',
  'Upload':                          'Upload',
  'Copiar':                          'Copy',
  'Colar':                           'Paste',
  'Cortar':                          'Cut',
  'Desfazer':                        'Undo',
  'Refazer':                         'Redo',
  'Selecionar':                      'Select',
  'Selecionar tudo':                 'Select all',
  'Publicar':                        'Publish',
  'Rascunho':                        'Draft',
  'Publicado':                       'Published',
  'Arquivado':                       'Archived',
  'Pendente':                        'Pending',
  'Processando':                     'Processing',
  'Concluído':                       'Completed',
  'Falhou':                          'Failed',
  'Novo':                            'New',
  'Nova':                            'New',
  'Padrão':                          'Default',
  'Avançado':                        'Advanced',
  'Básico':                          'Basic',
  'Geral':                           'General',
  'Segurança':                       'Security',
  'Permissões':                      'Permissions',
  'Perfil':                          'Profile',
  'Conta':                           'Account',
  'Notificações':                    'Notifications',
  'Integrações':                     'Integrations',
  'Integração':                      'Integration',
  'Conexão':                         'Connection',
  'Conectar':                        'Connect',
  'Desconectar':                     'Disconnect',
  'Sincronizar':                     'Sync',
  'Atualizar':                       'Update',
  'Histórico':                       'History',
  'Logs':                            'Logs',
  'Relatório':                       'Report',
  'Dashboard':                       'Dashboard',
  'Painel':                          'Panel',
  'Sidebar':                         'Sidebar',
  'Menu':                            'Menu',
  'Início':                          'Home',
  'Ajuda':                           'Help',
  'Documentação':                    'Documentation',
  'Suporte':                         'Support',
  'Sobre':                           'About',
  'Versão':                          'Version',
  'Licença':                         'License',
  'Termos de uso':                   'Terms of use',
  'Política de privacidade':         'Privacy policy',
  'Ambiente de produção':            'Production environment',
  'Ambiente de desenvolvimento':     'Development environment',
  'Ambiente de homologação':         'Staging environment',
  'Produção':                        'Production',
  'Desenvolvimento':                 'Development',
  'Homologação':                     'Staging',
  'Habilitar':                       'Enable',
  'Desabilitar':                     'Disable',
  'Obrigatório':                     'Required',
  'Opcional':                        'Optional',
  'Público':                         'Public',
  'Privado':                         'Private',
  'Interno':                         'Internal',
  'Externo':                         'External',
  'Entrada':                         'Input',
  'Saída':                           'Output',
  'Parâmetros':                      'Parameters',
  'Parâmetro':                       'Parameter',
  'Resposta':                        'Response',
  'Requisição':                      'Request',
  'Autenticação':                    'Authentication',
  'Autorização':                     'Authorization',
  'Chave de API':                    'API Key',
  'URL base':                        'Base URL',
  'Cabeçalho':                       'Header',
  'Corpo':                           'Body',
  'Método':                          'Method',
  'Rota':                            'Route',
  'Rotas':                           'Routes',
  'Endpoint':                        'Endpoint',
  'Endpoints':                       'Endpoints',
  'Implantação':                     'Deployment',
  'Publicação':                      'Publishing',
  'Especificação':                   'Specification',
  'Gateway':                         'Gateway',
  'Documentação':                    'Documentation',
  'Chat IA':                         'AI Chat',
  'Conectado':                       'Connected',
  'Desconectado':                    'Disconnected',
  'Enviar':                          'Send',
  'Nova versão':                     'New version',
  'NOME DA API':                     'API NAME',
  'PRINCIPAL':                       'MAIN',
  'SECUNDÁRIA':                      'SECONDARY',
  'CATEGORIA':                       'CATEGORY',
  'FORMATO':                         'FORMAT',
  'CRIADO POR':                      'CREATED BY',
  'DATA DE CRIAÇÃO':                 'CREATION DATE',
  'Detalhes da Especificação':       'Specification Details',
  'Corrente':                        'Current',
  'API Builder IA':                  'AI API Builder',
  'Pré-visualizar':                  'Preview',
  'Pré visualizar':                  'Preview',
  'Veículos':                        'Vehicles',
  'Releases':                        'Releases',
  'Lançamentos':                     'Releases',
  'Implantação':                     'Deployment',
  'Publicação':                      'Publishing',
  'Configuração':                    'Settings',
};

const selected = figma.currentPage.selection[0];
if (!selected) { figma.notify('Selecione um frame.', { error: true }); return; }

const textNodes = selected.findAll(n => n.type === 'TEXT');
let count = 0;
let errors = 0;

for (const node of textNodes) {
  const translated = translations[node.characters];
  if (!translated) continue;

  try {
    const len = node.characters.length;
    const fontSet = new Set();
    for (let i = 0; i < len; i++) {
      fontSet.add(JSON.stringify(node.getRangeFontName(i, i + 1)));
    }
    for (const fStr of fontSet) {
      await figma.loadFontAsync(JSON.parse(fStr));
    }

    const firstFont  = node.getRangeFontName(0, 1);
    const firstSize  = node.getRangeFontSize(0, 1);
    const firstFills = node.getRangeFills(0, 1);

    node.characters = translated;
    node.setRangeFontName(0, translated.length, firstFont);
    node.setRangeFontSize(0, translated.length, firstSize);
    node.setRangeFills(0, translated.length, firstFills);

    count++;
  } catch (e) {
    errors++;
  }
}

const ptPattern = /[ãçêôáéíóúàâõÃÇÊÔÁÉÍÓÚÀÂÕ]/;
const missed = textNodes
  .filter(n => !translations[n.characters] && ptPattern.test(n.characters))
  .map(n => JSON.stringify(n.characters));

if (missed.length > 0) {
  const preview = missed.slice(0, 3).join(' | ');
  figma.notify(`${count} traduzido(s). Faltam ${missed.length}: ${preview}`, { timeout: 15000 });
} else {
  figma.notify(`${count} traduzido(s)${errors ? `, ${errors} erro(s)` : ''}. Nenhum PT restante!`);
}
